name: Keep Render Active

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every hour at the top of the hour

jobs:
  ping:
    runs-on: ubuntu-latest  # Uses a virtual machine running Ubuntu

    steps:
      - name: Send HTTP Request
        run: curl -I https://real-code-editor-4yx6.onrender.com/
